### ISSUE TITLE
Conflicts with mpv-discord due to ipc socket

### ISSUE THREAD

**Issue by sitiom** [datasone/MPVMediaControl#11]
Currently, this plugin works inconsistently with mpv-discord due to the two plugins overriding the socket name.

mpv-discord names the socket to `mpv-discord-{pid}` while this plugin names it to `mpvsocket_{pid}`, perhaps there should be configurable option to change this format. Instead of sending the pid to the program, send the socket name instead and let `notify_media.lua` format it first with the pid in. That way, I can ideally set something like `socket_path=mpvsocket_{pid}` in the conf file.

**Comment by sitiom** [comment]
I have created a PR in mpv-discord (https://github.com/tnychn/mpv-discord/pull/46). Setting `socket_path=mpvsocket_{pid}` to match the naming here should now work, but ideally the plugin here should have the same configurable option.

**Comment by datasone** [comment]
Thanks for your advice on configurable socket name :D

**Comment by sitiom** [comment]
Please update the readme with the new socket parameter as well

**Comment by datasone** [comment]
Yes, thanks for reminding!
