### ISSUE TITLE
mpv's input.conf keybinds are overridden when window is not in focus

### ISSUE THREAD

**Issue by conradsrc** [datasone/MPVMediaControl#16]
I have my `input.conf` set so my forward/backwards/next/prev media keys seek forward and backwards 10 seconds instead of moving on to the next item in the playlist. I almost never want to do the latter, but this lets me easily skip backwards or forwards without alt+tabbing fullscreen applications like games.

```
FORWARD seek 10
REWIND seek -10
NEXT seek 10      #previously playlist-next
PREV seek -10     #previously playlist-prev
```

This works perfectly... if mpv is in focus, which is why I was looking up a solution similar to your project. It does work in the sense that my media keys are now hooked into SMTC and can control mpv when it's not in focus, but unfortunately it overrides mpv's keybinds and `NEXT` and `PREV` go back to their default behavior of toggling the playlist.

Is there anyway this can be changed to use mpv's keybindings instead of hardcoding this value, or is this a limitation of SMTC?

Thanks! Even if anything can't be done about this I'll still use it since "partial control if mpv isn't in focus" is better than "no control".

![image](https://github.com/datasone/MPVMediaControl/assets/8204892/b8a59c15-0cd2-4c88-bcbe-72ca750d05eb)

**Comment by datasone** [comment]
The media keys operation are controlled by sending commands to mpv ([Here](https://github.com/datasone/MPVMediaControl/blob/af9695f98e8b221a31fa5ff4ec1b5893a524069c/MPVMediaControl/MediaController.cs#L243)), so they don't obey input configuration.

I think we could make the sent commands configurable for people to remap the features (just the same as those in `input.conf`, where mpv commands are used to remap keys).

It shouldn't be hard to implement, so hopefully it may be accomplished soon.

**Comment by datasone** [comment]
0.2.2 is released, and you can just configure command sent to mpv with it.

**Comment by conradsrc** [comment]
Works perfectly, thanks. For anyone else using this, the `MPVMediaControl.exe` has a tray icon and you can right click it and select `Edit media control commands`.
