### ISSUE TITLE
Doesn't work on external links

### ISSUE THREAD

**Issue by WhoMI7** [datasone/MPVMediaControl#5]
Doesn't work on any external link.
Tested: Youtube links through yt-dlp, Direct downloadable links.

Logs:

          
[logs.txt](https://github.com/datasone/MPVMediaControl/files/8206749/logs.txt)

**Comment by datasone** [comment]
Fixed in release [0.1.0](https://github.com/datasone/MPVMediaControl/releases/tag/0.1.0)
